### ISSUE TITLE
create a repository and move API call there. Do not call API directly in viewmodel

### ISSUE THREAD

**Issue by sshettyn** [Ashraff0712/RetrofitProject#2]
https://github.com/Ashraff0712/RetrofitProject/blob/729eeb91f2ce16dd530852d9892d5ebfc1f09df1/app/src/main/java/com/example/retrofitproject/viewmodel/HomeViewModel.kt#L18

**Comment by Ashraff0712** [comment]
created a repository named Home Activity Repository and moved the API call there
